language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction
  - vendor/bin/install-phalcon.sh 2.0.x

script:
  - vendor/bin/phpunit

notifications:
  email: false